config/routes.rb
For30days::Application.routes.draw do

  resources :user_potentials, only: [:create]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resource :tasks, only: [:create]

  resources :users, path: "profile" do
    resources :tasks, path: "goals" do
      get 'start'     => 'tasks#start', :as => 'start'
      get 'completed' => 'tasks#completed', :as => 'completed'
      get 'missed'    => 'tasks#missed', :as => 'missed'

      resources :task_logs, path: "days" do
        resource :journal, except: [:show] #task logs also have journal entries
      end        

      resource :journal, except: [:show] #tasks have journal entries

    end

    resources :history, only: [:index]
  end

  root 'home#index'

end

app/models/user_potential.rb
class UserPotential < ActiveRecord::Base
end

app/controllers/user_potentials_controller.rb
class UserPotentialsController < ApplicationController
  before_action :set_user_potential, only: [:show, :edit, :update, :destroy]

  # GET /user_potentials
  # GET /user_potentials.json
  def index
    @user_potentials = UserPotential.all
  end

  # GET /user_potentials/1
  # GET /user_potentials/1.json
  def show
  end

  # GET /user_potentials/new
  def new
    @user_potential = UserPotential.new
  end

  # GET /user_potentials/1/edit
  def edit
  end

  # POST /user_potentials
  # POST /user_potentials.json
  def create
    @user_potential = UserPotential.new(user_potential_params)

    respond_to do |format|
      if @user_potential.save
        format.html { redirect_to :back, notice: 'Thank you for registering. We will notify you once we launch.' }
        format.json { render action: 'show', status: :created, location: @user_potential }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_potential.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_potentials/1
  # PATCH/PUT /user_potentials/1.json
  def update
    respond_to do |format|
      if @user_potential.update(user_potential_params)
        format.html { redirect_to @user_potential, notice: 'User potential was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_potential.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_potentials/1
  # DELETE /user_potentials/1.json
  def destroy
    @user_potential.destroy
    respond_to do |format|
      format.html { redirect_to user_potentials_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_potential
      @user_potential = UserPotential.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_potential_params
      params.require(:user_potential).permit(:email)
    end
end

app/helpers/user_potentials_helper.rb
module UserPotentialsHelper
end

app/views/user_potentials/_form.html.erb
<%= form_for(@user_potential) do |f| %>
  <% if @user_potential.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_potential.errors.count, "error") %> prohibited this user_potential from being saved:</h2>

      <ul>
      <% @user_potential.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_potentials/edit.html.erb
<h1>Editing user_potential</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_potential %> |
<%= link_to 'Back', user_potentials_path %>

app/views/user_potentials/index.html.erb
<h1>Listing user_potentials</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_potentials.each do |user_potential| %>
      <tr>
        <td><%= user_potential.email %></td>
        <td><%= link_to 'Show', user_potential %></td>
        <td><%= link_to 'Edit', edit_user_potential_path(user_potential) %></td>
        <td><%= link_to 'Destroy', user_potential, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User potential', new_user_potential_path %>

app/views/user_potentials/new.html.erb
<h1>New user_potential</h1>

<%= render 'form' %>

<%= link_to 'Back', user_potentials_path %>

app/views/user_potentials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user_potential.email %>
</p>

<%= link_to 'Edit', edit_user_potential_path(@user_potential) %> |
<%= link_to 'Back', user_potentials_path %>