config/routes.rb
For30days::Application.routes.draw do

  resources :user_potentials, only: [:create]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resource :tasks, only: [:create]

  resources :users, path: "profile" do
    resources :tasks, path: "goals" do
      get 'start'     => 'tasks#start', :as => 'start'
      get 'completed' => 'tasks#completed', :as => 'completed'
      get 'missed'    => 'tasks#missed', :as => 'missed'

      resources :task_logs, path: "days" do
        resource :journal, except: [:show] #task logs also have journal entries
      end        

      resource :journal, except: [:show] #tasks have journal entries

    end

    resources :history, only: [:index]
  end

  root 'home#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :user

  has_many :task_logs
  
  has_one :journal, :as => :journable

  #We are 1 indexed
  def day_count
    (self.start_date - Date.today.in_time_zone(self.user.time_zone).to_date).abs.round + 1
  end

  def has_conflicts?
    current_start_date = self.start_date


    Task.where(status: ['inactive', 'active']).where(user_id: self.user.id).where("id <> ?", self.id).each do |t|

      if current_start_date >= t.start_date and current_start_date < t.start_date + 30.days
        return true
      end
    end
    
    false
  end

  def marked_today?
    
    return true if todays_log.present?

    return false
    
  end

  def todays_log
    #get User's Time
    Time.use_zone self.user.time_zone do
      user_time = Time.zone.now
      mysql_tz_name = ActiveSupport::TimeZone[self.user.time_zone].tzinfo.name

      #Convert everything to user's local time, otherwise things get funky
      return self.task_logs.where(
                              "DATE(CONVERT_TZ(created_at, 'UTC', '#{mysql_tz_name}')) = ?",
                              user_time.to_date
                            ).first

    end

  end

  class << self
    #display_name
    def display_name
      "Goal"
    end

    def display_name_s
      display_name + "s"
    end

    def display_name_long
      "30 Day #{display_name}"
    end

    def display_name_s_long
      display_name_long + "s"
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:create]

  # GET /tasks
  # GET /tasks.json
  def index
    if params[:user_id].present?
      load_new_task
      @tasks = Task.where(user_id: params[:user_id])
      
    else
      @tasks = Task.all
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    load_new_task
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create

    #We have to run our own auth here
    unless user_signed_in?
      session[:task] = params[:task]

      redirect_to new_user_session_url
      return
    end

    @task = Task.new(task_params)
    @task.user_id = current_user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to :back, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to user_tasks_url }
      format.json { head :no_content }
    end
  end

  # Other things =====================================================
  def start
    @task = Task.find(params[:task_id])

    respond_to do |format|
      unless @task.has_conflicts?
        @task.update_attributes({
          status: "active",
          start_date: Time.now.in_time_zone(@task.user.time_zone).to_date
        })

        msg = "Awesome, let's go tackle - #{@task.name}"

        format.html { redirect_to :back, notice: msg}
        format.json { render json: { :task => @task, message: msg } }
      else

        msg = "Sorry there's already an active task! Let's finish that one first."

        format.html { redirect_to :back, alert: msg}
        format.json { render json: { :task => @task, message: msg } }
      end
    end

  end

  # Daily Task Completion ============================================
  def completed
    @task = Task.find(params[:task_id])

    respond_to do |format|
      unless @task.marked_today?
        @tasklog = TaskLog.create( task_id: @task.id, user_id: current_user.id, status: "completed")

        msg = "#{@task.name} completed today, good job!"

        
        format.html { redirect_to :back, notice: msg}
        format.json { render json: { :task_log => @tasklog, message: msg } }
        
      else
        msg = "This you already marked this as completed today."

        #also need to be able to respond to 30+ days
        format.html { redirect_to :back, alert: msg}
        format.json { render json: { :message => msg, :status => "failed" } }
      end
    end

  end

  def missed

    respond_to do |format|
      unless @task.marked_today?
        @tasklog = TaskLog.create( task_id: @task.id, user_id: current_user.id, status: "missed")

        msg = "Sorry, you missed #{@task.name} today."

        
        format.html { redirect_to :back, notice: msg}
        format.json { render json: { :task_log => @tasklog, message: msg } }
        
      else
        msg = "This you already marked this as missed today."

        #also need to be able to respond to 30+ days
        format.html { redirect_to :back, alert: msg}
        format.json { render json: { :message => msg, :status => "failed" } }
      end
    end
  end


  protected
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def load_new_task
      @task = Task.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_daily_task_mark_journal.html.haml
.daily-task-mark-journal

  -unless @current_task.marked_today?
    Justin, were you able to
    =surround '"', '"' do
      =@current_task.name
    today?

    =link_to "Yes", user_task_completed_url(current_user.id, @current_task.id), class: "btn btn-success"
    =link_to "No", user_task_missed_url(current_user.id, @current_task.id), class: "btn btn-default"
  -else
    %p
      Great work completing Day
      =@current_task.day_count

    %h2
      Write about It

    =form_for @journal, :url => user_task_task_log_journal_url({user_id: current_user.id, task_id: @current_task.id, task_log_id: @current_task_log.id }) do |f|
      =f.text_area :text

      =f.submit

app/views/tasks/_form.html.haml
.row
  .span12
    =form_for [current_user, task], html: { class: "form-horizontal", role: "form"} do |f|
      - if task.errors.any?
        #error_explanation.alert.alert-danger
          %h2
            = pluralize(task.errors.count, "error")
            prohibited this task from being saved:
          %ul
            - task.errors.full_messages.each do |msg|
              %li= msg
      .form-group
        %label.col-sm-2.control-label{:for => "name"}
          ="Daily #{Task.display_name}"
        .col-sm-4
          = f.text_field :name, id: "new-goal-name", class: "col-sm-4 form-control", placeholder: "Tackle This"

      .form-group
        .col-sm-offset-2.col-sm-10
          %button.submit.btn.btn-primary{type: "submit"}
            -unless params[:action] == "edit"
              ="Create New #{Task.display_name_long}"
            -else
              ="Update #{Task.display_name}"

app/views/tasks/_no_active_tasks.html.haml
-if @inactive_tasks.present?
  %table.table
    %thead
      %tr
        %th
        %th
          Name
        %th
    -@inactive_tasks.to_enum.with_index(1).each do |t, index|
      %tr
        %td
          ="#{index}."
        %td
          =t.name
        %td
          =link_to "Start", user_task_start_url(current_user.id, t.id), class: "btn btn-success"

-else
  %h1
    You have no tasks yet. Let's start one!

    =render :partial => "tasks/form", :locals => {:task => @new_task}

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render partial: 'form', locals: { task: @task } %>

<%= link_to 'Back', user_tasks_path(current_user.id) %>

app/views/tasks/index.html.haml
.page-header
  %h1
    %small
      I want to
    =surround '"', '"' do
      %span#do-this="Tackle This"
    %small
      each day for 30 days
= render partial: 'form', locals: { task: @task }

%h1="Your #{Task.display_name_s_long}"
%table.table
  %thead
    %tr
      %th Name
      %th Date Started
      %th
      %th
  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.name
        %td= task.start_date.strftime("%b %d, %Y") if task.start_date.present?
        %td= link_to 'Edit', edit_user_task_path(current_user.id, task)
        %td= link_to 'Destroy', user_task_path(current_user.id, task), method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to "New #{Task.display_name_long}", new_user_task_path(current_user.id)

app/views/tasks/new.html.haml
.page-header
  %h1
    %small
      I want to
    =surround '"', '"' do
      %span#do-this="Tackle This"
    %small
      each day for 30 days
= render 'form'
= link_to 'Back', tasks_path

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>