config/routes.rb
For30days::Application.routes.draw do

  resources :user_potentials, only: [:create]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resource :tasks, only: [:create]

  resources :users, path: "profile" do
    resources :tasks, path: "goals" do
      get 'start'     => 'tasks#start', :as => 'start'
      get 'completed' => 'tasks#completed', :as => 'completed'
      get 'missed'    => 'tasks#missed', :as => 'missed'

      resources :task_logs, path: "days" do
        resource :journal, except: [:show] #task logs also have journal entries
      end        

      resource :journal, except: [:show] #tasks have journal entries

    end

    resources :history, only: [:index]
  end

  root 'home#index'

end

app/views/shared/_navbar_main.html.haml
%nav.navbar.navbar-default.navbar-top{role: "navigation"}
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: root_url} For 30 Day.es
    / Collect the nav links, forms, and other content for toggling
    .collapse.navbar-collapse.navbar-ex1-collapse
      %ul.nav.navbar-nav
        %li
          = link_to "Home", root_url
        -if user_signed_in?
          %li
            =link_to Task.display_name_s, user_tasks_url(current_user.id)

      %ul.nav.navbar-nav.navbar-right
        -if user_signed_in?
          %li

            = link_to "#{(image_tag current_user.profile_picture, class: "nav_profile_pic") if current_user.profile_picture.present?} #{current_user.display_name}".html_safe, user_url(current_user.id), class: "nav_profile"
          %li.dropdown
            %a{:href => "#", :class => "dropdown-toggle", :"data-toggle" => "dropdown"}
              .glyphicon.glyphicon-cog
            %ul.dropdown-menu
              %li
                = link_to "Profile", user_url(current_user.id)
              %li
                = link_to "Edit", edit_user_url(current_user.id)
              %li
                = link_to "Log Out", destroy_user_session_url, :method => :delete
        -elsif params[:controller] != "devise/sessions" && @coming_soon != true 
          %li
            = link_to "<span class='btn-auth btn-facebook'>Sign in with <b>Facebook</b></span>".html_safe, user_omniauth_authorize_path(:facebook)